import {useEffect,useMemo,useState} from 'react'
import {ArrowLeft,ArrowRight,Check,RotateCcw,ShieldCheck,Sparkles} from 'lucide-react'
import {categoryMeta,questions,sideQuests,type Category} from './data'
type Screen='home'|'quiz'|'analyzing'|'results'|'sprint';type Answers=Record<number,number>
const options=['Never','Sometimes','Often','🔥 Production incident'];const categories=Object.keys(categoryMeta) as Category[]
function scoresFor(a:Answers){return Object.fromEntries(categories.map(c=>{const qs=questions.filter(q=>q.category===c);return[c,Math.round(qs.reduce((s,q)=>s+(a[q.id]??0),0)/(qs.length*3)*100)]})) as Record<Category,number>}
export default function App(){
 const[screen,setScreen]=useState<Screen>('home'),[index,setIndex]=useState(0),[started,setStarted]=useState(false)
 const[answers,setAnswers]=useState<Answers>(()=>{try{return JSON.parse(localStorage.getItem('human-runtime-answers')||'{}')}catch{return{}}})
 const scores=useMemo(()=>scoresFor(answers),[answers]);const primary=useMemo(()=>categories.reduce((a,b)=>scores[a]>=scores[b]?a:b),[scores]);const quest=useMemo(()=>sideQuests[questions.reduce((n,q)=>n+(answers[q.id]??0),0)%sideQuests.length],[answers])
 useEffect(()=>localStorage.setItem('human-runtime-answers',JSON.stringify(answers)),[answers])
 const answer=(v:number)=>{setAnswers({...answers,[questions[index].id]:v});if(index<questions.length-1)setTimeout(()=>setIndex(index+1),180);else{setScreen('analyzing');setTimeout(()=>setScreen('results'),2300)}}
 const reset=()=>{localStorage.removeItem('human-runtime-answers');setAnswers({});setIndex(0);setStarted(false);setScreen('home')}
 if(screen==='home')return <main className="shell hero"><div className="terminal-tag"><span>●</span> human-runtime v1.0</div><div className="hero-icon">⌁</div><p className="eyebrow">HUMAN TECH DEBT SCANNER</p><h1>Your most important<br/><em>production system</em> is you.</h1><p className="lead">Run a 3-minute diagnostic across focus, recovery, movement, AI habits and life outside work.</p><button className="primary" onClick={()=>setScreen('quiz')}>RUN DIAGNOSTIC <ArrowRight size={18}/></button><div className="privacy"><ShieldCheck size={17}/> Private by default. Your individual answers stay on this device.</div><div className="code-card"><code>$ human-runtime inspect --self</code><br/><span>Ready to scan 5 subsystems...</span></div></main>
 if(screen==='quiz'){const q=questions[index];return <main className="shell quiz"><header><button className="icon-btn" onClick={()=>index?setIndex(index-1):setScreen('home')}><ArrowLeft/></button><span>CHECK {String(index+1).padStart(2,'0')}/{questions.length}</span><span>{Math.round((index+1)/questions.length*100)}%</span></header><div className="progress"><i style={{width:`${(index+1)/questions.length*100}%`}}/></div><section className="question-card"><p className="eyebrow">INSPECTING HUMAN RUNTIME...</p><h2>{q.text}</h2><div className="options">{options.map((label,v)=><button key={label} className={answers[q.id]===v?'selected':''} onClick={()=>answer(v)}><span>{v}</span>{label}<Check size={18}/></button>)}</div></section><p className="joke">{['Garbage collector cannot reclaim meetings.','Human CPU does not support infinite threads.','Coffee is not a dependency injection framework.','Your brain has entered thermal throttling.'][index%4]}</p></main>}
 if(screen==='analyzing')return <main className="shell analyzing"><div className="spinner">⌁</div><h2>Analyzing human runtime...</h2><div className="checks"><p>Scanning context switches... <b>✓</b></p><p>Checking recovery cycles... <b>⚠</b></p><p>Inspecting AI dependency... <b>✓</b></p><p>Finding background processes... <b>⚠</b></p></div><div className="progress"><i className="animate"/></div></main>
 if(screen==='sprint')return <main className="shell"><div className="terminal-tag"><span>●</span> HR-{String(scores[primary]).padStart(3,'0')}</div><p className="eyebrow">HUMAN RUNTIME SPRINT #1</p><h1>Ship one <em>refactor.</em></h1><div className="issue"><span className="status">IN PROGRESS</span><h2>{categoryMeta[primary].icon} {categoryMeta[primary].label}</h2><p className="muted">7-day experiment</p><p className="experiment">{categoryMeta[primary].refactor}</p><hr/><p><b>Success signal</b><br/>At the end of the week, ask: “Did this make my runtime feel better?”</p></div><button className="primary" onClick={()=>setStarted(true)}>{started?'SPRINT STARTED ✓':'START EXPERIMENT'} <Sparkles size={18}/></button><button className="secondary" onClick={()=>setScreen('results')}><ArrowLeft size={17}/> Back to report</button></main>
 const m=categoryMeta[primary];return <main className="shell results"><div className="result-head"><div><p className="eyebrow">ANALYSIS COMPLETE</p><h1>Human Runtime<br/><em>Report</em></h1></div><div className="health">● OPERATIONAL<br/><span>REFACTOR RECOMMENDED</span></div></div><section className="score-card">{categories.map(c=><div className="score" key={c}><span>{categoryMeta[c].icon} {categoryMeta[c].label}</span><div className="bar"><i style={{width:`${scores[c]}%`}}/></div><b>{scores[c]}%</b></div>)}</section><section className="diagnosis"><p className="eyebrow">PRIMARY TECH DEBT</p><h2>{m.icon} {m.label}</h2><code>{m.error}</code><p>{m.insight}</p></section><div className="recommend-grid"><section><p className="eyebrow">⚡ PATCH NOW</p><p>{m.patch}</p></section><section><p className="eyebrow">🛠 REFACTOR THIS SPRINT</p><p>{m.refactor}</p></section></div><section className="quest"><div className="quest-icon">{quest[0]}</div><div><p className="eyebrow">RANDOM SIDE QUEST</p><h3>{quest[1]}</h3><p>{quest[2]}</p></div></section><button className="primary" onClick={()=>setScreen('sprint')}>SHIP ONE REFACTOR <ArrowRight size={18}/></button><button className="secondary" onClick={reset}><RotateCcw size={17}/> Run diagnostic again</button><p className="disclaimer">Reflection tool only — not a medical or psychological assessment.</p></main>
}