export type Category='focus'|'recovery'|'physical'|'ai'|'disconnect'
export type Question={id:number;text:string;category:Category}
export const questions:Question[]=[
{id:1,category:'focus',text:'After several meetings or context switches, I struggle to return to deep coding.'},{id:2,category:'focus',text:'Slack, Teams, email, notifications, or people interrupt me while I’m trying to concentrate.'},{id:3,category:'focus',text:'I jump between tickets, PRs, meetings and messages so often that my brain feels like 37 browser tabs.'},
{id:4,category:'recovery',text:'I start coding before I feel properly rested.'},{id:5,category:'recovery',text:'I sacrifice sleep because of work, screens, gaming, doom-scrolling, or “just one more thing.”'},{id:6,category:'recovery',text:'By the end of the workday, my brain feels too drained for anything mentally demanding.'},
{id:7,category:'physical',text:'I can spend 2+ hours coding without standing up or moving much.'},{id:8,category:'physical',text:'I regularly notice neck, back, wrist, eye, or posture discomfort while working.'},{id:9,category:'physical',text:'Most days, work leaves little room for walking, exercise, sports, or meaningful movement.'},
{id:10,category:'ai',text:'My first reaction to a difficult coding problem is asking AI before thinking through it myself.'},{id:11,category:'ai',text:'I sometimes accept AI-generated code before I could confidently explain why it works.'},{id:12,category:'ai',text:'Without AI, some development tasks now feel harder than they used to.'},
{id:13,category:'disconnect',text:'After closing my laptop, I continue mentally debugging work.'},{id:14,category:'disconnect',text:'A large part of my free time simply becomes more screen time.'},{id:15,category:'disconnect',text:'During a normal week, I don’t spend enough time doing things completely unrelated to software.'}]
export const categoryMeta:Record<Category,{label:string;icon:string;error:string;insight:string;patch:string;refactor:string}>={
focus:{label:'Focus',icon:'🧠',error:'TooManyInterruptionsException',insight:'Your attention may be spending more time switching branches than shipping code.',patch:'Mute notifications for one 60-minute coding block tomorrow.',refactor:'Protect one 60–90 minute deep-work block on at least four days this week.'},
recovery:{label:'Recovery',icon:'🔋',error:'HumanBatteryLowException',insight:'Your runtime may be borrowing energy from tomorrow to finish today.',patch:'Set a clear shutdown time tonight.',refactor:'Keep a consistent shutdown and sleep window for seven days.'},
physical:{label:'Physical',icon:'🪑',error:'SedentaryThreadWarning',insight:'Chair uptime is impressive. Your body may prefer slightly worse availability.',patch:'Take a five-minute movement break in the next hour.',refactor:'Move for five minutes every hour and take one walking meeting this week.'},
ai:{label:'AI Dependency',icon:'🤖',error:'HumanInTheLoop=false',insight:'AI should amplify your reasoning, not replace the reps that keep it sharp.',patch:'Before your next AI prompt, write your own hypothesis first.',refactor:'Use the 10-minute rule: understand, hypothesize and try before asking AI.'},
disconnect:{label:'Disconnect',icon:'📴',error:'ProcessStillRunningAfterExit',insight:'The laptop closed, but a few work processes may still be running in the background.',patch:'Write tomorrow’s first task, close work apps, then physically leave your workspace.',refactor:'Use a shutdown ritual and spend 30+ minutes daily doing something unrelated to software.'}}
export const sideQuests=[['🌳','Touch Grass — Literally','Take a 30-minute walk somewhere green without checking your phone.'],['🎵','Analog Streaming','Listen to an entire album from beginning to end without multitasking.'],['📚','Read Something Useless','Read 20+ pages of something that will not improve your career.'],['⚽','Enable Physics Engine','Play a sport or move for at least 30 minutes.'],['🍳','Deploy to Kitchen','Cook something you have never made before.'],['☕','Human API Call','Have coffee with someone and do not discuss work for 30 minutes.'],['🎨','Compile Nothing','Create something with absolutely no productivity goal.']]
